=== dsvasilkov/WinFormsEmployees/files/employees.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="Employees">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Employee" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Name" type="xs:string" minOccurs="1" />
                            <xs:element name="Surname" type="xs:string" minOccurs="1" />
                            <xs:element name="Patronymic" type="xs:string" minOccurs="0" />
                            <xs:element name="Gender" type="xs:string" minOccurs="0" />
                            <xs:element name="BirthDate" type="xs:date" minOccurs="0" />
                            <xs:element name="Address" type="xs:string" minOccurs="0" />
                            <xs:element name="PhoneNumber" type="xs:string" minOccurs="0" />
                            <xs:element name="Email" type="xs:string" minOccurs="0" />
                            <xs:element name="HireDate" type="xs:date" minOccurs="0" />
                            <xs:element name="INN" type="xs:string" minOccurs="0" />
                            <xs:element name="SNILS" type="xs:string" minOccurs="0" />
                            <xs:element name="PassportSeries" type="xs:string" minOccurs="0" />
                            <xs:element name="PassportNumber" type="xs:string" minOccurs="0" />
                            <xs:element name="PassportIssueDate" type="xs:date" minOccurs="0" />
                            <xs:element name="PassportIssueBy" type="xs:string" minOccurs="0" />
                            <xs:element name="PlaceOfReg" type="xs:string" minOccurs="0" />
                            <xs:element name="PhotoPath" type="xs:string" minOccurs="0" />
                            <xs:element name="BranchId" type="xs:int" minOccurs="0" />
                            <xs:element name="DepartmentId" type="xs:int" minOccurs="0" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== dsvasilkov/WinFormsEmployees/files/employee.xml
<?xml version="1.0" encoding="utf-8"?>
<Employees xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="employees.xsd">
    <Employee>
        <Name>Пётр</Name>
        <Surname>Петров</Surname>
        <Patronymic>Петрович</Patronymic>
        <Gender>М</Gender>
        <BirthDate>1985-06-15</BirthDate>
        <Address>Пр. Ленина, 1</Address>
        <PhoneNumber>89008001234</PhoneNumber>
        <Email>petr@example.com</Email>
        <HireDate>2020-01-10</HireDate>
        <INN>123456789111</INN>
        <SNILS>12345678900</SNILS>
        <PassportSeries>1234</PassportSeries>
        <PassportNumber>567890</PassportNumber>
        <PassportIssueDate>2005-04-20</PassportIssueDate>
        <PassportIssueBy>МВД</PassportIssueBy>
        <PlaceOfReg>Чебоксары</PlaceOfReg>
        <PhotoPath>C:\\Users\\Александр\\EmployeeFormsApp\\Photo\\Dog.jpg</PhotoPath>
        <BranchId>3</BranchId>
        <DepartmentId>1</DepartmentId>
    </Employee>
    <Employee>
        <Name>Екатерина</Name>
        <Surname>Яковлева</Surname>
        <Patronymic>Сергеевна</Patronymic>
        <Gender>Ж</Gender>
        <BirthDate>1990-09-25</BirthDate>
        <Address>Пр. Ивана Яковлева</Address>
        <PhoneNumber>89234567890</PhoneNumber>
        <Email>ekaterina@example.com</Email>
        <HireDate>2021-05-15</HireDate>
        <INN>987654321111</INN>
        <SNILS>98765432100</SNILS>
        <PassportSeries>4321</PassportSeries>
        <PassportNumber>098765</PassportNumber>
        <PassportIssueDate>2010-08-10</PassportIssueDate>
        <PassportIssueBy>МВД</PassportIssueBy>
        <PlaceOfReg>Чебоксары</PlaceOfReg>
        <PhotoPath>C:\\Users\\Александр\\EmployeeFormsApp\\Photo\\Dog.jpg</PhotoPath>
        <BranchId>3</BranchId>
        <DepartmentId>1</DepartmentId>
    </Employee>
     <Employee>
        <Name>Джон</Name>
        <Surname>Смит</Surname>
    </Employee>
</Employees>
